// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

 static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCfhF19wI_Pqet3qHh2EEFzWqOX6EMxJMk",
  authDomain: "ecorecycle-main-36efd.firebaseapp.com",
  projectId: "ecorecycle-main-36efd",
  
  // ★★★ 이 부분을 아래처럼 다시 통일합니다. (이전 .appspot.com에서 원복) ★★★
  storageBucket: "ecorecycle-main-36efd.firebasestorage.app", 
  
  messagingSenderId: "546077528698",
  appId: "1:546077528698:web:f00a41cc25291fbbba21c3",
  measurementId: "G-SLS74H6NV5", 
);
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qrl855Je6LW2pHNM9W40My03XNLL_7c',
    appId: '1:1050245469522:android:875d11153eca60183c168b',
    messagingSenderId: '1050245469522',
    projectId: 'ecorecycle-main-36efd',
    storageBucket: 'ecorecycle-2d900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRb0BVLawDdoEp_zvNn8nPJcu0HJFAaQ',
    appId: '1:1050245469522:ios:cef601fd8e6ae4cd3c168b',
    messagingSenderId: '1050245469522',
    projectId: 'ecorecycle-2d900',
    storageBucket: 'ecorecycle-2d900.firebasestorage.app',
    iosBundleId: 'com.example.airecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnRb0BVLawDdoEp_zvNn8nPJcu0HJFAaQ',
    appId: '1:1050245469522:ios:cef601fd8e6ae4cd3c168b',
    messagingSenderId: '1050245469522',
    projectId: 'ecorecycle-2d900',
    storageBucket: 'ecorecycle-2d900.firebasestorage.app',
    iosBundleId: 'com.example.airecycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxyUTiCeqN28MQrSATuvzwp7-A4sXCZzc',
    appId: '1:1050245469522:web:7b274655a6df1e603c168b',
    messagingSenderId: '1050245469522',
    projectId: 'ecorecycle-2d900',
    authDomain: 'ecorecycle-2d900.firebaseapp.com',
    storageBucket: 'ecorecycle-2d900.firebasestorage.app',
    measurementId: 'G-5H5GZL1QTH',
  );
}
